apiVersion: v1
kind: Namespace
metadata:
  name: me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: me
  labels:
    app: node
    name: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: node
        label: server
    spec: # pod spec
      containers:
        - name: node
          image: munhunger/me:server
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: me
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 32011
      targetPort: 3000
      name: node
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: me-ingress
  namespace: me
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - me.munhunger.com
      secretName: me-tls
  rules:
    - host: me.munhunger.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node
                port:
                  number: 3000
